
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
spring:
  application:
    name: loja
  banner:
    location: classpath:banner.txt    
  output:
    ansi:
      enabled: always

info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'       