server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/edernilson/microservice-config-repo.git
          search-paths: delivery-flowers/fornecedor
  banner:
    location: classpath:banner.txt
    
  output:
    ansi:
      enabled: always

info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'